version: 2.1
orbs:
  node: circleci/node@5.0.2
  heroku: circleci/heroku@1.2.6

jobs:
  build_and_test:
    executor: node/default
    steps:
      - checkout
      - node/install-packages:
          pkg-manager: yarn

      - run:
          name: Upload screenshots to argos-ci.com
          command: yarn run argos upload ./screenshots

workflows:
  test_my_app:
    jobs:
      - build_and_test
